# Generated by Django 3.1.7 on 2021-07-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_follow_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='languages',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='sitename',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
